### ISSUE TITLE
Name of generated widget

### ISSUE THREAD

**Issue by subzero911** [rrousselGit/functional_widget#75] opened 2020-09-04 14:19 UTC
How about adding the name attribute?
`@swidget(name: 'MyCoolWidget')`

Also maybe add a configurable naming rule into `build.yaml`?
I thought about it, because builder methods are most often named like: `_buildHeader()`, `_buildDataList()`
But I want to have resulting widgets like `Header()` instead of `_BuildHeader()`

**Comment by rrousselGit** [comment] 2020-12-13 06:36
Duplicate of #70

**Closed by rrousselGit** 2020-12-13 06:36 UTC
